---
baseURL: "https://nippervice.netlify.com/"
languageCode: "en-us"
title: "Clare Evans"

menu:
  main:
    - Name: "About"
      URL: "/about/"
    - Name: "Portfolio"
      URL: "/portfolio/"

taxonomies:
  service: "services"

---
